[package]
name = "rust-drive"
version = "0.1.0"
edition = "2021"

[dependencies]
r2r = "0.9.2"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3"
rand = "0.8.5"
nalgebra = "0.33.1"
parking_lot = "*"
